package customdecoder
// Copyright 2026 dotandev
// SPDX-License-Identifier: Apache-2.0































































}	return &CustomDecoder{}, nilfunc NewPluginFactory() (plugin.DecoderPlugin, error) {// Export the factory function for dynamic loading}	}		Description: "Example custom event decoder for proprietary formats",		EventTypes:  []string{"custom.event", "proprietary.format"},		APIVersion:  plugin.Version,		Version:     d.Version(),		Name:        d.Name(),	return plugin.PluginMetadata{func (d *CustomDecoder) Metadata() plugin.PluginMetadata {}	return json.Marshal(decoded)	}		Plugin:  d.Name(),		Value:   payload.Value,		Type:    payload.Type,		Decoded: true,	}{		Plugin  string `json:"plugin"`		Value   string `json:"value"`		Type    string `json:"type"`		Decoded bool   `json:"decoded"`	decoded := struct {	}		return nil, fmt.Errorf("invalid payload: %w", err)	if err := json.Unmarshal(data, &payload); err != nil {	}		Value string `json:"value"`		Type  string `json:"type"`	var payload struct {func (d *CustomDecoder) Decode(data []byte) (json.RawMessage, error) {}	return eventType == "custom.event" || eventType == "proprietary.format"func (d *CustomDecoder) CanDecode(eventType string) bool {}	return "1.0.0"func (d *CustomDecoder) Version() string {}	return "custom-decoder"func (d *CustomDecoder) Name() string {type CustomDecoder struct{})	"github.com/dotandev/hintents/internal/plugin"	"fmt"	"encoding/json"import (package main